# Generated by Django 3.1 on 2020-09-15 16:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
